### ISSUE TITLE
Envoy hangs when starting after upgrading to Contour 0.12.0

### ISSUE THREAD

**Issue by jipperinbham** [heptio/contour#1091] opened 2019-05-14 20:38 UTC
**What steps did you take and what happened:**

We use the hostnet-ds-split topology and with all pods happy and healthy, if we terminate an envoy pod, it gets recreated but then just sits on the following log line:

```
[2019-05-14 20:24:55.018][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:113] cm init: initializing secondary clusters
```

Logs from the two contour pods when the envoy pod was deleted:

<details><summary>contour pod 1</summary>

```
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=16 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=20 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=25 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=28 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=4 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=6 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=31 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=24 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=22 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=27 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=23 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=10 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=26 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=11 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=30 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=29 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=21 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=3 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=12 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=15 context=grpc error="context canceled"
time="2019-05-14T20:24:52Z" level=error msg="stream terminated" connection=18 context=grpc error="context canceled"
```
</details>

<details><summary>contour pod 2</summary>

```
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=1 context=grpc error_detail=nil resource_names="[]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.Cluster version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=1 context=grpc count=16 error_detail=nil resource_names="[]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.Cluster version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=1 context=grpc error_detail=nil resource_names="[]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.Cluster version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=4 context=grpc error_detail=nil resource_names="[development/kubedashian-31/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=10 context=grpc error_detail=nil resource_names="[development/kubedashian-58/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=3 context=grpc error_detail=nil resource_names="[development/kubedashian-30/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=9 context=grpc error_detail=nil resource_names="[development/kubedashian-40/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=11 context=grpc error_detail=nil resource_names="[development/kubedashian-55/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=9 context=grpc count=0 error_detail=nil resource_names="[development/kubedashian-40/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=5 context=grpc error_detail=nil resource_names="[development/kubedashian-37/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=5 context=grpc count=0 error_detail=nil resource_names="[development/kubedashian-37/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=5 context=grpc error_detail=nil resource_names="[development/kubedashian-37/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=2 context=grpc error_detail=nil resource_names="[development/kubedashian-29/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=2 context=grpc count=0 error_detail=nil resource_names="[development/kubedashian-29/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=2 context=grpc error_detail=nil resource_names="[development/kubedashian-29/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=6 context=grpc error_detail=nil resource_names="[development/kubedashian-33/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=6 context=grpc count=0 error_detail=nil resource_names="[development/kubedashian-33/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=6 context=grpc error_detail=nil resource_names="[development/kubedashian-33/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=9 context=grpc error_detail=nil resource_names="[development/kubedashian-40/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=12 context=grpc error_detail=nil resource_names="[development/kubedashian-62/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=12 context=grpc count=1 error_detail=nil resource_names="[development/kubedashian-62/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=12 context=grpc error_detail=nil resource_names="[development/kubedashian-62/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=17 context=grpc error_detail=nil resource_names="[development/shipt-test-app-6/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=17 context=grpc count=1 error_detail=nil resource_names="[development/shipt-test-app-6/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=17 context=grpc error_detail=nil resource_names="[development/shipt-test-app-6/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=13 context=grpc error_detail=nil resource_names="[development/kubedashian-70/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=13 context=grpc count=1 error_detail=nil resource_names="[development/kubedashian-70/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=13 context=grpc error_detail=nil resource_names="[development/kubedashian-70/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=14 context=grpc error_detail=nil resource_names="[development/shipt-credits-118/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=14 context=grpc count=1 error_detail=nil resource_names="[development/shipt-credits-118/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=14 context=grpc error_detail=nil resource_names="[development/shipt-credits-118/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=4 context=grpc count=0 error_detail=nil resource_names="[development/kubedashian-31/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=4 context=grpc error_detail=nil resource_names="[development/kubedashian-31/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=15 context=grpc error_detail=nil resource_names="[development/shipt-test-app-4/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=15 context=grpc count=1 error_detail=nil resource_names="[development/shipt-test-app-4/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=15 context=grpc error_detail=nil resource_names="[development/shipt-test-app-4/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=16 context=grpc error_detail=nil resource_names="[development/shipt-test-app-5/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=16 context=grpc count=1 error_detail=nil resource_names="[development/shipt-test-app-5/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=16 context=grpc error_detail=nil resource_names="[development/shipt-test-app-5/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=10 context=grpc count=1 error_detail=nil resource_names="[development/kubedashian-58/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=10 context=grpc error_detail=nil resource_names="[development/kubedashian-58/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=8 context=grpc error_detail=nil resource_names="[development/kubedashian-54/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=8 context=grpc count=0 error_detail=nil resource_names="[development/kubedashian-54/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=8 context=grpc error_detail=nil resource_names="[development/kubedashian-54/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=3 context=grpc count=0 error_detail=nil resource_names="[development/kubedashian-30/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=3 context=grpc error_detail=nil resource_names="[development/kubedashian-30/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=7 context=grpc error_detail=nil resource_names="[development/kubedashian-32/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=7 context=grpc count=0 error_detail=nil resource_names="[development/kubedashian-32/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=7 context=grpc error_detail=nil resource_names="[development/kubedashian-32/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=response connection=11 context=grpc count=1 error_detail=nil resource_names="[development/kubedashian-55/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
time="2019-05-14T20:24:55Z" level=info msg=stream_wait connection=11 context=grpc error_detail=nil resource_names="[development/kubedashian-55/http]" response_nonce= type_url=type.googleapis.com/envoy.api.v2.ClusterLoadAssignment version_info=
```
</details>

In order to get envoy unstuck, we have to delete the contour pods after which we get the following envoy logs:

<details><summary>envoy logs post contour pod deletion</summary>

```
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.243][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:137] cm init: all clusters initialized
[2019-05-14 20:26:39.243][1][info][main] [source/server/server.cc:462] all clusters initialized. initializing init manager
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 14, upstream connect error or disconnect/reset before headers. reset reason: connection termination
[2019-05-14 20:26:39.243][1][info][config] [source/server/listener_manager_impl.cc:1006] all dependencies initialized. starting workers
[2019-05-14 20:26:39.243][1][warning][config] [bazel-out/k8-opt/bin/source/common/config/_virtual_includes/grpc_stream_lib/common/config/grpc_stream.h:101] gRPC config stream closed: 13,
[2019-05-14 20:26:39.478][1][info][upstream] [source/server/lds_api.cc:74] lds: add/update listener 'ingress_http'
[2019-05-14 20:26:39.500][1][info][upstream] [source/server/lds_api.cc:74] lds: add/update listener 'ingress_https'
```
</details>

**What did you expect to happen:**

When an envoy pod gets deleted or restarted, it comes back up happy and healthy.

**Anything else you would like to add:**

We're only seeing this on 1 cluster and have not had the issue with 2 others but currently on hold rolling it out further until we understand the root cause. 

**Environment:**

- Contour version: 0.12.0
- Kubernetes version: (use `kubectl version`): v1.11.8
- Kubernetes installer & version: kops v1.11.1
- Cloud provider or hardware configuration: AWS
- OS (e.g. from `/etc/os-release`): Debian Stretch

**Comment by davecheney** [comment] 2019-05-14 20:40
Thank you for your issue report. Does downgrading to 0.11 fix the problem?

**Comment by jipperinbham** [comment] 2019-05-14 20:45
Yes, when downgrading to Contour v.011.0 and Envoy v1.9.1 we do no experience the issue.

**Comment by davecheney** [comment] 2019-05-15 01:27
@jipperinbham  I think I have an idea what is going wrong, would you be able to briefly (just until it wedges) upgrade to Contour 0.12 by set the log level to `debug`

```yaml
        - --log-level debug  
```

If this is related to the configuration Contour 0.12 is sending, this should wedge almost immediately, but at least we'll have debug logging up to that point. Then you can revert to `info` level logging and Contour 0.11

**Comment by jipperinbham** [comment] 2019-05-15 13:00
I tried the above but looks like the flag is not defined?

```
contour: error: unknown long flag '--log-level debug', try --help
```

**Comment by davecheney** [comment] 2019-05-15 13:05
This flag is on the envoy container, it adjusts the logging level for envoy.

**Comment by jipperinbham** [comment] 2019-05-15 13:05
🤦‍♂ trying again...

**Comment by jipperinbham** [comment] 2019-05-15 13:17
attached envoy logs
[envoy-logs.txt](https://github.com/heptio/contour/files/3182651/envoy-logs.txt)

**Comment by jipperinbham** [comment] 2019-05-15 13:41
I finally hit the issue on another cluster to try and find some sort of correlation. The only thing that seemed to be similar across clusters is they both have empty endpoints for which an IngressRoute has been defined. The deployment(s) were scaled to 0 as part of some testing going on.

**Comment by davecheney** [comment] 2019-05-15 23:06
Thank you, that is great context, that gives me something to go on to repro the problem.

**Comment by davecheney** [comment] 2019-05-17 01:25
I've been able to reproduce the problem locally. The simple repro is to scale a service to zero replicas and restart envoy. 

This is another symptom of #439 and #420.

**Comment by davecheney** [comment] 2019-05-20 07:42
It's EOD here so I wanted to write a brief sitrep for the watchers of the ticket.

The underlying issue is Envoy can ask two different types of questions about a set of xDS resources; the first is "give me everything in this cache", the other is "you told me to ask you about a resource named X". The former is issued by LDS and CDS, the latter is used by RDS and EDS. Specifically when Envoy starts up it asked LDS for all the listeners registered, from there it will find the names of the routes and clusters mentioned by name, for RDS it issues a specific query saying "you told me there was a route table called `ingress_http`, tell me about its details". 

The same occurs for EDS however because EDS is handled separately by Contour we don't know ahead of time, when we mention an EDS entry by name in CDS if it actually exists. Why wouldn't it exist, because of services that have been scaled to zero. If you have a service which has zero replicas the Endpoint document for that service will exist but be empty. Because it is empty, we have no information to populate the EDS tables with -- however, because the linkage between CDS and EDS is by cluster name, not the dag, if you have a valid service document, Contour can generate a Cluster entry that points to EDS but there is no entry in the EDS table.

(Why don't we process EDS entries in the dag? Because there are too many of them and they change too often. There are also more subtle problems that scaling a service to zero is a common pattern in k9s, it means "this service is still configured, it just has no healthy replicas at the moment", this is different to deleting the service. By extension if we were to place EDS information int the dag, when a service's endpoints scaled to zero, either deliberately with a replication controller, or transiently with a pod restarting, could potentially mean that a route has no valid services, if a route has no valid services, we don't serve it, and if there are no valid routes in a virtual host, then we don't serve that either, and if there are no virtualhosts for a listener, then we close it #389. The result could be the brownian motion of pods coming and going could result in listeners flapping up and down. This is precisely _not_ what happens when you scale a service to zero, so even though it is inconvenient to have EDS handled separately wrt. this issue, it _is_ the right way to do it.)

The underlying problem is the [xDS specification](https://www.envoyproxy.io/docs/envoy/latest/api-docs/xds_protocol) is mute on what to do when Envoy asks for a resource that Contour knows nothing about. This comes back to the two ways that Envoy can ask this question. The first, _list all the entries you know about_, is easy, if its not in Contour's tables, we can't send it back to Envoy, and that's ok because Envoy didn't know about it in the first place. The second way, Envoy has been told there is an entry in the EDS tables from the CDS tables, so it's asking by name. In #420 and #439 we tried to address this problem, but it remains. It turns out the answer is even if Contour doesn't know anything about an EDS entry that Envoy asks for, specifically, then it has to lie, it has to return an empty entry -- this is the difference between no glass of water, and an empty glass of water -- in both cases you don't get a drink, but in the first case you sit around thinking you haven't been served yet, and this is the problem for Envoy.

The changes landed on Friday and today set the stage to push the two different ways Envoy can ask for information down far enough that if EDS is asked for a resource by name, we can make up the right information; basically a `ClusterLoadAssignment` record with zero entries. This is the work remaining tomorrow to close this ticket.

Also, we'll be doing a 0.12.1 release as soon as this change is landed on master because this problem is pretty severe -- it can block startup of any deployed contour if there is a service that has been scaled to zero -- and we're not planning on releasing 0.13 for at least a month.

**Comment by davecheney** [comment] 2019-05-21 07:56
@jipperinbham I think I have a fix for this problem. If you don't want to wait for #1110 to be merged, you can try `docker.io/davecheney/contour:latest` which contains the fix.

**Comment by jipperinbham** [comment] 2019-05-21 13:38
@davecheney thanks for the quick fix! I've just tested the docker image on one of the clusters and everything looks to be working as expected with zero length Endpoints. 

Given the amount of commits to master since v0.12.0, will you be able to release a v0.12.1 with just this fix?

**Closed** 2019-05-21 23:20 UTC
Labels: bug, p0 - Hair On Fire

**Comment by davecheney** [comment] 2019-05-21 23:22
@jipperinbham thanks for confirming. yeah, doing a 0.12.1 backport won't be the most enjoyable thing I've done this week but I've kept a record of all the dependant changes so it shouldn't be that hard to do.

Thanks again for reporting this issue, in retrospect its been festering for many releases, and I'm very grateful for the push to address it properly.
