### ISSUE TITLE
Redirect to https via global flag configuration

### ISSUE THREAD

**Issue by sudeeptoroy** [heptio/contour#981] opened 2019-04-05 14:13 UTC
**Describe the solution you'd like**
On nginx with this [config](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#server-side-https-enforcement-through-redirect) we can configure global https redirect enforcement. We need a similar configuration for contour.

once redirect is configured, we can skip http endpoint creation too. 

**Anything else you would like to add:**
We need to validate each IngressRoute as user can configure "spec.routes.permitInsecure" and allow a http connection via contour. We would like to avoid this validation by a global configuration not exposed to users. 

**Environment:**

- Contour version: all
- Kubernetes version: (use `kubectl version`): all
- Kubernetes installer & version: all
- Cloud provider or hardware configuration: all
- OS (e.g. from `/etc/os-release`): all

**Comment by stevesloka** [comment] 2019-04-05 14:56
Hey @sudeeptoroy, IngressRoutes by default will enforce the 301 redirect automatically. There is a scenario where users can allow insecure which is I think what you are getting at. 

Closing as dupe of #864

**Closed by stevesloka** 2019-04-05 14:56 UTC

**Comment by sudeeptoroy** [comment] 2019-04-05 15:24
Of course IngressRoute does redirect automatically, I should have made it explicit that the behaviour is observed for "ingress" resource configuration. 

#864 does take care of spec.routes.permitInsecure issue with IngressRoute resource

shall I edit this issue or open a new one?
