### ISSUE TITLE
Contour does not delete IngressRoute metrics even after IngressRoute has been deleted

### ISSUE THREAD

**Issue by yutaokaz** [heptio/contour#611] opened 2018-08-09 13:03 UTC
I found that Contour set IngressRoute metrics to 1 even if IngressRoute is deleted. I expected Contour does not return IngressRoute metrics about deleted IngressRoute.

I tried as bellow.
1. I create IngressRoute and confirm Contour create metrics: `contour_ingressroute_total{namespace}`  and set it to 1.
2. I delete IngressRoute, but metrics: `contour_ingressroute_total{namespace}` is still alive and set to 1.

I think this issue is caused by not initializing variables in `Metrics.SetIngressRouteMetric()`. And now I think Contour should initialize IngressRoute metrics variables before call `Metrics.SetIngressRouteMetric()` when updating metrics.

**Comment by rosskukulinski** [comment] 2018-08-09 15:22
Ha! I also just opened #612.  These may be related.

**Comment by rosskukulinski** [comment] 2018-08-14 00:41
Closing as duplicate of #612 which @stevesloka is already working on.

**Closed by rosskukulinski** 2018-08-14 00:41 UTC
Labels: bug, p1 - Important
