### ISSUE TITLE
Remove deprecated `envoy-external` flags

### ISSUE THREAD

**Issue by youngnick** [heptio/contour#1141] opened 2019-05-31 00:45 UTC
As of #1125 these flags (`envoy-external-http-port` and `envoy-external-https-port`) are deprecated, this is work to remove them completely, per the deprecation notice.

**Comment by davecheney** [comment] 2019-05-31 04:29
Assigning to 0.14. I'll make this as help wanted because its a well defined issue for anyone to contribute too. If anyone is interested in this please do not start til the 0.14 cycle is open.

**Comment by odacremolbap** [comment] 2019-06-27 13:34
I'd like to tackle this one

btw, current parsing for both flags is logging a deprecation warn for `0.14` and doing nothing with those vars.
https://github.com/heptio/contour/blob/master/cmd/contour/contour.go#L172-L178

I don't know if that's the intended behaviour, I would expect those vars to be working despite the warning. I'll read the history of the issue, I'm sure I'm missing something.

Anycase, please assign me the deletion of those ~ 20 lines

**Comment by odacremolbap** [comment] 2019-06-27 13:39
I guess this change will require a changelog entry.

How do you manage changelogs? Is there a file I should add an entry to, a label, or some other automated mechanism?

**Comment by davecheney** [comment] 2019-06-27 14:21
Go for it.

For changelogs I generate the release notes by hand from the issues and PRs in the milestone.

**Closed** 2019-06-27 22:16 UTC
Labels: good first issue, help wanted, p2 - Long-term Important, tech-debt
