### ISSUE TITLE
Envoy does not close HTTP(S) listener when the last IngressRoute is removed

### ISSUE THREAD

**Issue by alexbrand** [heptio/contour#1346] opened 2019-08-16 21:13 UTC
**What steps did you take and what happened:**
1. Install contour:
```shell
kubectl apply -f https://raw.githubusercontent.com/heptio/contour/v0.14.2/examples/render/deployment-rbac.yaml
```

2. Scale deployment to 1 to aid in debugging

```shell
kubectl -n heptio-contour scale deployment contour --replicas=1
```

3. Create sample application with the following IngressRoute

```yaml
apiVersion: contour.heptio.com/v1beta1
kind: IngressRoute
metadata:
  name: simple-app
  namespace: simple-app
spec:
  virtualhost:
    fqdn: simple-app.127.0.0.1.nip.io
  routes:
  - match: '/'
    services:
    - name: simple-app
      port: 80
```

4. Verify that the application is reachable

5. Delete the IngressRoute

**What did you expect to happen:**
Given that there are no IngressRoutes defined, Envoy should not have a listener open on port 8080.

**Anything else you would like to add:**
To verify whether Envoy is listening on port 8080 (Not sure if there is a better way):
1. SSH onto the node where Envoy is running
2. Get envoy's process ID
3. nsenter into envoy's network namespace (`nsenter -t $envoy_pid -n bash`)
4. Run `netstat -tupln` (Assuming netstat is installed on the node)

Netstat output before creating IngressRoute:

```shell
$ netstat -tupln | grep envoy
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      38791/envoy
tcp        0      0 0.0.0.0:8002            0.0.0.0:*               LISTEN      38791/envoy
```

Netstat output after creating IngressRoute:

```shell
$ netstat -tupln | grep envoy
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      38791/envoy
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      38791/envoy
tcp        0      0 0.0.0.0:8002            0.0.0.0:*               LISTEN      38791/envoy
```

Netstat output after removing the IngressRoute (still listening on 8080):

```shell
$ netstat -tupln | grep envoy
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      38791/envoy
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      38791/envoy
tcp        0      0 0.0.0.0:8002            0.0.0.0:*               LISTEN      38791/envoy
```

Another interesting tidbit is that the Contour DAG seems to be correct (i.e. empty) after removing the IngressRoute:

```shell
$ curl localhost:6060/debug/dag
digraph DAG {
rankdir="LR"
}
```

**Environment:**

- Contour version: `v0.14.1`
- Envoy version: `v1.11.1`
- Kubernetes version: (use `kubectl version`): 
```shell
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.0", GitCommit:"e8462b5b5dc2584fdcd18e6bcfe9f1e4d970a529", GitTreeState:"clean", BuildDate:"2019-06-25T23:41:27Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by davecheney** [comment] 2019-08-29 07:22
@alexbrand would you please retest with `v0.15.0` or `master`. Thank you.

**Comment by alexbrand** [comment] 2019-08-29 13:35
I followed the above repro steps and verified that this still happens in `master`. 

I also noticed in that the Recv-Q for Envoy's port 8080 grows as I send requests to that port. (See screenshot)

![image](https://user-images.githubusercontent.com/545723/63944792-35bff100-ca40-11e9-8a37-d219b9f14770.png)

**Comment by davecheney** [comment] 2019-08-30 00:28
@alexbrand thanks for confirming.

**Comment by davecheney** [comment] 2019-08-30 00:41
I think i've confirmed this. Something seems to be holding `ingress_http` open, `ingress_https` disappears as expected when the last TLS vhost disappears.

**Comment by davecheney** [comment] 2019-08-30 00:59
ok, this was PEBKAC, I had an ingressroute hanging around.

@alexbrand I'm not able to reproduce this locally. Could you go to the troubleshooting page and grab the config_dump, if you have an `ingress_http` dynamic listener, then there should be at least one route entry in the `ingress_http` route table.

**Comment by alexbrand** [comment] 2019-08-30 02:07
Hey @davecheney, I just looked into the config_dump at three different stages: 1) a fresh contour instance, 2) after creating the ingressroute, and 3) after deleting the ingressroute. 

I found that in:
1) The `ingress_http` listener does not show up in the configmap (as expected).
2) The `ingress_http` listener shows up under `dynamic_active_listeners` (as expected)
3) The `ingress_http` listener shows up under `dynamic_draining_listeners` (maybe expected?)

It seems like the listener moves to a draining state but stays there? It's also interesting that you cannot reproduce.

The following gist has the config_dump JSON files for the above three stages: https://gist.github.com/alexbrand/b214b93221691874a405ea555d50012a

**Comment by davecheney** [comment] 2019-08-30 02:08
this route is holding port 80 open, https://gist.github.com/alexbrand/b214b93221691874a405ea555d50012a#file-02-with-ingressroute-json-L397

**Comment by alexbrand** [comment] 2019-08-30 02:16
That's the `config_dump` that I captured while the IngressRoute was defined, so I do expect that route to be defined. 

The following `config_dump` is the one that I grabed after deleting the ingressroute: https://gist.github.com/alexbrand/b214b93221691874a405ea555d50012a#file-03-post-delete-json.  It does not contain that route, but does have the ingress_http listener here: https://gist.github.com/alexbrand/b214b93221691874a405ea555d50012a#file-03-post-delete-json-L273

**Comment by alexbrand** [comment] 2019-08-30 02:21
Okay. If I wait long enough the listener is eventually removed. It seems like the drain takes ~ 2 minutes:

```
[2019-08-30 02:07:40.566][1][info][upstream] [source/server/lds_api.cc:60] lds: add/update listener 'ingress_http'
[2019-08-30 02:07:40.567][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:495] add/update cluster simple-app/simple-app/80/da39a3ee5e starting warming
[2019-08-30 02:07:40.569][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:507] warming cluster simple-app/simple-app/80/da39a3ee5e complete
[2019-08-30 02:07:59.812][1][info][upstream] [source/common/upstream/cluster_manager_impl.cc:548] removing cluster simple-app/simple-app/80/da39a3ee5e
[2019-08-30 02:07:59.813][1][info][upstream] [source/server/lds_api.cc:42] lds: remove listener 'ingress_http'
[2019-08-30 02:10:06.765][1][info][main] [source/server/drain_manager_impl.cc:63] shutting down parent after drain
```

Unless you think this drain is taking longer than it should, I think we can close this issue.

**Comment by davecheney** [comment] 2019-08-30 03:55
There will be a delay between the listener configuration going away and
envoy closing the socket -- it probably won't accept any new connections on
that socket while its in draining mode.

I'm not able to reproduce what you see -- as soon as the last ingress_http
route goes away, the listener is immediately removed from
127.0.0.1:9001/listeners in my cluster

**Comment by alexbrand** [comment] 2019-08-30 12:06
Got it. I think we can close this issue, as Envoy does eventually drain and close the port when the last IngressRoute is removed.

**Comment by davecheney** [comment] 2019-09-03 02:49
Thanks @alexbrand let's call this case closed for the moment.

**Closed by davecheney** 2019-09-03 02:49 UTC
Labels: bug, p1 - Important, waiting for info
