### ISSUE TITLE
ingressroute: add CORS support

### ISSUE THREAD

**Issue by glerchundi** [heptio/contour#465] opened 2018-06-25 21:20 UTC
Feature request to add CORS support in `IngressRoute`. Envoy already supports this at ~route~ virtual host level so it seems to be plausible to add it on the `virtualhost` section, something like:

```
[...]
    tls:
      # required, the name of a secret in the current namespace
      secretName: google-tls
      # other properties like cipher suites may be added later
    # if present describes the CORS policy.
    cors:
      # Specifies the origins that will be allowed to do CORS requests.
      allowOrigin:
        - www.google.com
        - google.com
      # Specifies the content for the *access-control-allow-methods*
      # header.
      allowMethods:
        - GET
        - POST
      # Specifies the content for the *access-control-allow-headers*
      # header.
      allowHeaders:
        - Content-Type
      # Specifies the content for the *access-control-expose-headers*
      # header.
      exposeHeaders:
        - Content-Type
      # Specifies the content for the *access-control-max-age* header.
      maxAge: 24h
      # Specifies whether the resource allows credentials.
      allowCredentials: true
  strategy: RoundRobin # (Optional) LB Algorithm to apply to all services, defaults for all services
[...]
```

WDYT @davecheney?

**Comment by rosskukulinski** [comment] 2018-06-25 21:30
Hi @glerchundi - thanks for opening up this issue.

Does CORS definition ever need to be configured for a specific path? (e.g. `/login` has different CORS than `/blog`) . I'm wondering if this is a property of the top-level and/or maybe needs to support over-riding at the path level.

**Comment by glerchundi** [comment] 2018-06-25 21:38
That was fast @rosskukulinski thanks for the prompt response.

AFAIK, Envoy doesn't support different CORS policies for paths in the same virtual host. [Take a look at this protobuf definition](https://github.com/envoyproxy/envoy/blob/master/api/envoy/api/v2/route/route.proto#L97).

Without knowing the internals of Contour (how this maps `IngressRoute` to Envoy entitieS) does this answer your question?

**Comment by rosskukulinski** [comment] 2018-07-06 20:28
Dupe of #437.  Would be implemented in ingressroute regardless.

**Closed by rosskukulinski** 2018-07-06 20:28 UTC
