### ISSUE TITLE
Support wild cards in Contour

### ISSUE THREAD

**Issue by tbhat05** [heptio/contour#1050] opened 2019-04-25 20:58 UTC
Envoy supports wild cards in path whereas contour doesn't
e.g:, for the below
/v1alpha/clusters/C01D87GHYXFKE44RQETJTS8PRV7/scanner
the C01D8* is a cluster-id and can vary from one cluster to another
Currently, we can't specify - /v1alpha/clusters/*/scanner
in contour to be generic for all cluster-ids. Thus, I should be able to route:
/v1alpha/clusters/*/test
/v1alpha/clusters/*/scan

to two different services by using wildcards in the path.

**Environment:**

- Contour version: all
- Kubernetes version: (use `kubectl version`): all
- Kubernetes installer & version:all
- Cloud provider or hardware configuration:all
- OS (e.g. from `/etc/os-release`):all

**Comment by davecheney** [comment] 2019-05-06 05:12
Thank you for raising this issue. At the moment Contour only supports prefix matching because of the interaction with delegation. We'll need to do a design document before proceeding here has different forms of matching will interact with with delegation.

**Comment by davecheney** [comment] 2019-06-20 01:32
I am closing this as a duplicate of #1179. We understand the request for wildcard matching. We are working towards this as part of #1075 with a target of 0.15.

**Closed by davecheney** 2019-06-20 01:32 UTC
Labels: Needs Product, enhancement
