### ISSUE TITLE
Support HTTP2 ingress.kubernetes.io/secure-backends: "true"

### ISSUE THREAD

**Issue by andrewwebber** [heptio/contour#569] opened 2018-07-21 16:39 UTC
I am considering migrating from [https://github.com/zlabjp/nghttpx-ingress-lb](nghttpx-ingress-lb) which has served me well as one of the first http2/grpc ingress controller.

From a security point of view, proxying a secure backend is critical for me as well as controlling HTTP2/HTTP1.1 protocols. 

nghttpx-ingress-lb accomplished this with the following annotations .

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gateway-https
  annotations:
    ingress.kubernetes.io/secure-backends: "true"
    ingress.zlab.co.jp/backend-config: '{"push": {"8013": {"proto": "http/1.1", "tls": true, "dns": true}}, "gateway": {"443": {"proto": "h2", "tls": true, "dns": true}}}'
```

**Comment by davecheney** [comment] 2018-07-23 10:04
Thanks for raising this issue. 

> ingress.kubernetes.io/secure-backends: "true"

Did you mean nginx.ingress.kubernetes.io/secure-backends: "true" ? See https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md

For ingress.zlab.co.jp/backend-config:, contour already supports some of the aspects of this as an annotation on the service object, https://github.com/heptio/contour/blob/master/docs/annotations.md#contour-specific-service-annotations

I'm going to mark this as 0.7 to continue the discussion. I'm afraid I won't be able to look at it for the 0.6 cycle.

**Comment by andrewwebber** [comment] 2018-07-23 10:11
My understanding was that **ingress.kubernetes.io/secure-backends** was not nginx specific but ingress controller agnostics.

A vault operator [example](https://coreos.com/tectonic/docs/latest/vault-operator/user/ingress.html)
```yaml
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: vault
  namespace: default
  annotations:
    ingress.kubernetes.io/secure-backends: 'true'
    kubernetes.io/ingress.class: tectonic
spec:
  tls:
    - hosts:
        - vault.ingress.staging.core-os.net
      secretName: vault-server-ingress-tls
  rules:
    - host: vault.ingress.staging.core-os.net
      http:
        paths:
          - path: /
            backend:
              serviceName: example
              servicePort: 8200
```

**Comment by davecheney** [comment] 2018-07-23 10:17
Thanks. You're probably right, but dang those annotations are hard to
google.

**Comment by stephenmoloney** [comment] 2019-01-02 17:57
I think it's `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"` now.

**Comment by kskewes** [comment] 2019-03-11 02:35
Not sure if this is still active or related but `secure-backends` has been deprecated and removed in current nginx-ingress versions. 
See: https://github.com/kubernetes/ingress-nginx/issues/3416

**Comment by andrewwebber** [comment] 2019-03-11 06:59
@kskewes what's your recommendation for ensuring TLS between the ingress controller and the backend K8 services

**Comment by kskewes** [comment] 2019-03-11 07:15
Sorry I should have posted updated docs link too: https://github.com/kubernetes/ingress-nginx/blob/master/docs/user-guide/nginx-configuration/annotations.md#backend-protocol

**Comment by andrewwebber** [comment] 2019-03-11 07:25
Forgive me if I miss understood but it seems strange to use an annotation with your product that begins with Nginx. I was expecting ingress.kubernetes.io/secure-backends would be a vendor neutral choice

**Comment by kskewes** [comment] 2019-03-11 07:33
I'm just an end user and came across this by search about `secure-backends`. Hope haven't derailed issue :)

**Comment by andrewwebber** [comment] 2019-03-11 07:46
@kskewes hey no problem :) I was just hoping you had already guidance on this issue resolving this issue.
So what your saying is that the final annotation for contour should be something like contour.ingress.kubernetes.io/backend-protocol: "HTTPS" if I am correct?

When using nghttpx the syntax is kinda proprietor
```yaml
ingress.zlab.co.jp/backend-config: '{"hello-srv": {"443": {"proto": "h2", "tls": true}}}'
```

**Comment by kskewes** [comment] 2019-03-11 07:54
No sorry. There are a few similar issues to this one. See https://github.com/heptio/contour/issues/406 etc .

**Comment by andrewwebber** [comment] 2019-03-11 08:04
@kskewes that is an excellent reference, I must have miss that related issue. I will continue to track that instead, thanks!

**Comment by bitsofinfo** [comment] 2019-03-25 16:45
@andrewwebber what solution did you end up using to get this to proxy to a TLS upstream backend?

**Comment by andrewwebber** [comment] 2019-03-25 18:22
@bitsofinfo I have never found a solution to this problem with contour. 

My solution is currently using nghttp ingress controller as it supports this use case.

https://github.com/zlabjp/nghttpx-ingress-lb

**Comment by davecheney** [comment] 2019-04-05 00:43
Closing as duplicate of #406 which has an assignee.

**Closed by davecheney** 2019-04-05 00:43 UTC
Labels: enhancement, help wanted, p2 - Long-term Important
